[graph]
all-features = true

[advisories]
version = 2
yanked = "warn"
ignore = []

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unicode-DFS-2016",
  "Unicode-3.0",
  "Zlib",
  "CC0-1.0",
  "MPL-2.0",
  "OpenSSL",
]
confidence-threshold = 0.8

[[licenses.exceptions]]
allow = ["OpenSSL"]
name = "ring"

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[bans.build]
executables = "allow"
interpreted = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
  "https://github.com/tauri-apps/fix-path-env-rs",
]

[sources.allow-org]
github = []
